---
baseURL: https://takaung.netlify.app/
languageCode: en-us
title: First Takaung
theme: First Takaung
paginate: "9"
copyright: A template by [First Takaung](https://www.takaung.com "Your most friendly developer")
googleAnalytics: # Enter Google Analytics ie. UA-012345678-9
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
outputs:
  home:
  - HTML
  - RSS
  - JSON
minify:
  disableCSS: false
  disableHTML: false
  disableJS: false
  disableJSON: false
  disableSVG: false
  disableXML: false
  minifyOutput: true
  tdewolff:
    html:
      keepWhitespace: false

params:
  analytics:
    google:
      SiteVerificationTag: # Google Site Verification
    yandex:
      SiteVerificationTag: # Yandex Site Verification
    bing:
      SiteVerificationTag: # Bing Site Verification
  env: production
  author: Than Htike Aung
  description: First Takaung Company Website
  math: false
  images:
  - "/uploads/og.webp"
  label:
    title: _First Takaung_
    text: Welcome to First Takaung Ltd.
    lightNavIcon: /uploads/sun.svg
    darkNavIcon: /uploads/zap.svg
    iconHeight: "35"
    iconWIdth: "35"
  comments: true
  mainSections:
  - product
  ShowShareButtons: true
  ShowCodeCopyButtons: true
  ShowRelated: true
  CookieNotice: We use cookies to improve your experience on our site and to show
    you relevant advertising.
  CookieLink: /legal/privacy/#cookies-and-web-beacons
  CookieButton: Cookies Policy
  disableAnchoredHeadings: false
  contactFormAction: # Get link from https://formsubmit.io or https://fabform.io
  assets:
    disableFingerprinting: false
    favicon: /uploads/zap.svg
    favicon16x16: /uploads/zap.svg
    favicon32x32: /uploads/zap.svg
    apple_touch_icon: /uploads/zap.svg
    safari_pinned_tab: /uploads/zap.svg
  ShowReadingTime: true
  ShowBreadCrumbs: true
  homepage:
    # Hero Section
    disableHeroSection: false
    heroUpperTitle: 
    heroTitle: First Takaung
    heroDescription: Company with innovative ideas
    heroCTAPrimaryText: Blog
    heroCTAPrimaryUrl: "/blog/"
    heroCTASecondaryText: Contact Us
    heroCTASecondaryUrl: "/contact/"
    heroBackgroundImage: "/uploads/portfolio-1.webp"
    # Blog Section
    disableBlogSection: false
    blogTitle: Our Products
    blogDescription: This is our products
    seeMoreText: More Products
    # About Section    
    disableAboutSection: false
    aboutTitle: Our Motto
    aboutDescription: Empowering Tomorrow, One Byte at a Time
    aboutImgUrl: "/uploads/self.webp"
    aboutContent: our mission to drive positive change through technology. We believe that every line of code, every algorithm, and every digital innovation contributes to a brighter future. With unwavering commitment, we harness the power of bytes to create solutions that transform industries, elevate lives, and pave the way for progress. Join us on this journey as we shape tomorrow, byte by byte.
    # Portfolio Section
    disablePortfolioSection: false
    portfolioTitle: Services
    portfolioDescription: Some of our services
    portfolio:
    - imageUrl: /uploads/portfolio-1.webp
      alt: # image alt for better SEO
      description: Technical Training
      websiteUrl: #
    - imageUrl: /uploads/portfolio-2.webp
      alt: # image alt for better SEO
      description: Customized Business Solution
      websiteUrl: #
    - imageUrl: /uploads/portfolio-3.webp
      alt: # image alt for better SEO
      description: Mobile App Development
      websiteUrl: #
  # Search Options (https://fusejs.io/)
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: "0"
    distance: "1000"
    threshold: "0.4"
    minMatchCharLength: "0"
    keys:
    - title
    - permalink
    - summary
    - content
  plugins:
    css:
    - link: plugins/css/pico.min.css
    js:
    - link: plugins/js/feather.min.js
menus:
  main: # Main Menu
  - name: Products
    title: Products
    pre: pen-tool
    url: "/product"
    weight: "20"
  - name: Search
    title: Search
    pre: search
    url: "/search"
    weight: "30"
  - name: Contact
    title: Contact
    pre: mail
    url: "/contact"
    weight: "40"
  - name: Github
    title: 
    pre: github
    url: https://github.com/orgs/Takaung
    weight: "50"
  search: # Search page's quick links
  - name: Categories
    title: Categories
    url: "/categories"
    weight: "10"
  - name: Archives
    title: Archives
    url: "/archives"
    weight: "20"
  - name: Tags
    title: Tags
    url: "/tags"
    weight: "30"
